name: modeltest
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.1
  - pysocks=1.7.1
  - python=3.10.16
  - requests=2.32.3
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiometer==1.0.0
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anthropic==0.51.0
      - anyio==4.9.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - backoff==2.2.1
      - bert-score==0.3.13
      - cachetools==5.5.2
      - charset-normalizer==3.4.2
      - click==8.2.0
      - cohere==5.15.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - coverage==7.8.0
      - cycler==0.12.1
      - decorator==5.2.1
      - distro==1.9.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - fastavro==1.10.0
      - filelock==3.18.0
      - fonttools==4.58.0
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.0rc1
      - google-api-python-client==2.169.0
      - google-auth==2.40.1
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - grpcio==1.71.0
      - grpcio-status==1.71.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.31.2
      - idna==3.10
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - jiter==0.9.0
      - joblib==1.5.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - lxml==5.4.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mistralai==1.7.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.3
      - narwhals==1.39.1
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==2.2.5
      - openai==1.78.0
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.2.1
      - plotly==6.1.0
      - pluggy==1.6.0
      - portalocker==3.1.1
      - propcache==0.3.1
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - py==1.11.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pytest==8.3.5
      - pytest-cov==6.1.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - ray==2.46.0
      - referencing==0.36.2
      - regex==2024.11.6
      - retry==0.9.2
      - rich==14.0.0
      - rouge-score==0.1.2
      - rpds-py==0.24.0
      - rsa==4.9.1
      - sacrebleu==2.5.1
      - safetensors==0.5.3
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.7.0
      - tqdm==4.67.1
      - transformers==4.51.3
      - types-requests==2.32.0.20250515
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - uritemplate==4.1.1
      - urllib3==2.4.0
      - yarl==1.20.0