# Google Models Configuration

models:
  - name: gemini_1_5_pro
    display_name: "Gemini 1.5 Pro"
    version: "gemini-1.5-pro"
    api_key_env: "GOOGLE_API_KEY"
    max_tokens: 1000000
    context_window: 1000000
    strengths:
      - "Extremely long context window"
      - "Multimodal capabilities"
      - "Advanced reasoning"
    defaults:
      temperature: 0.7
      top_p: 0.95
      max_output_tokens: 8192
    cost:
      input_per_1k: 3.5
      output_per_1k: 10.0

  - name: gemini_1_5_flash
    display_name: "Gemini 1.5 Flash"
    version: "gemini-1.5-flash"
    api_key_env: "GOOGLE_API_KEY"
    max_tokens: 1000000
    context_window: 1000000
    strengths:
      - "Fast inference"
      - "Cost efficiency"
      - "Long context capabilities"
    defaults:
      temperature: 0.7
      top_p: 0.95
      max_output_tokens: 8192
    cost:
      input_per_1k: 0.35
      output_per_1k: 1.05

  - name: gemini_2_0_flash
    display_name: "Gemini 2.0 Flash"
    version: "gemini-2.0-flash"
    api_key_env: "GOOGLE_API_KEY"
    max_tokens: 1000000
    context_window: 1000000
    strengths:
      - "Latest Google capabilities"
      - "Balance of speed and quality"
      - "Enhanced instruction following"
    defaults:
      temperature: 0.7
      top_p: 0.95
      max_output_tokens: 8192
    cost:
      input_per_1k: 0.7
      output_per_1k: 2.1

  - name: gemini_2_0_flash_thinking
    display_name: "Gemini 2.0 Flash Thinking"
    version: "gemini-2.0-flash-thinking"
    api_key_env: "GOOGLE_API_KEY"
    max_tokens: 1000000
    context_window: 1000000
    strengths:
      - "Chain-of-thought capabilities"
      - "Enhanced reasoning"
      - "Step-by-step problem solving"
    defaults:
      temperature: 0.7
      top_p: 0.95
      max_output_tokens: 8192
    cost:
      input_per_1k: 0.7
      output_per_1k: 2.1

  - name: gemini_2_5_pro
    display_name: "Gemini 2.5 Pro"
    version: "gemini-2.5-pro"
    api_key_env: "GOOGLE_API_KEY"
    max_tokens: 1000000
    context_window: 1000000
    strengths:
      - "Cutting edge Google model"
      - "Best reasoning capabilities"
      - "Advanced multimodal understanding"
    defaults:
      temperature: 0.7
      top_p: 0.95
      max_output_tokens: 8192
    cost:
      input_per_1k: 7.0
      output_per_1k: 21.0